#!/usr/bin/env python3
"""Fetch Manrope from Google Fonts and rewrite it as local static assets.

The repository intentionally does not vendor font binaries. During installation or
Docker build this script downloads the requested Manrope webfont subsets, stores
those files under app/static/fonts/manrope/, and generates a local @font-face
stylesheet at app/static/css/manrope-local.css.
"""
from __future__ import annotations

import re
import sys
import time
from pathlib import Path
from urllib.error import URLError, HTTPError
from urllib.request import Request, urlopen

ROOT = Path(__file__).resolve().parents[1]
FONT_DIR = ROOT / "app" / "static" / "fonts" / "manrope"
CSS_PATH = ROOT / "app" / "static" / "css" / "manrope-local.css"
CSS_URL = "https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;600;700&display=swap"
UA = (
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
)


def _fetch(url: str, attempts: int = 3) -> bytes:
    last_error: Exception | None = None
    for attempt in range(1, attempts + 1):
        try:
            req = Request(url, headers={"User-Agent": UA, "Accept": "*/*"})
            with urlopen(req, timeout=30) as response:
                return response.read()
        except (URLError, HTTPError, TimeoutError) as exc:
            last_error = exc
            if attempt < attempts:
                time.sleep(attempt)
    raise RuntimeError(f"Unable to download {url}: {last_error}")


def _already_ready() -> bool:
    if not CSS_PATH.exists():
        return False
    css = CSS_PATH.read_text(encoding="utf-8", errors="ignore")
    if "@font-face" not in css or "Manrope" not in css:
        return False
    refs = re.findall(r"url\(['\"]?\.\./fonts/manrope/([^)'\"]+)", css)
    return bool(refs) and all((FONT_DIR / name).is_file() for name in refs)


def main() -> int:
    if _already_ready():
        print("Manrope local assets already present; skipping download.")
        return 0

    FONT_DIR.mkdir(parents=True, exist_ok=True)
    for old in FONT_DIR.glob("*.woff2"):
        old.unlink()

    css = _fetch(CSS_URL).decode("utf-8")
    urls = []
    for url in re.findall(r"url\((https://[^)]+\.woff2)\)", css):
        if url not in urls:
            urls.append(url)
    if not urls:
        raise RuntimeError("Google Fonts returned no Manrope WOFF2 URLs.")

    replacements: dict[str, str] = {}
    for index, url in enumerate(urls, start=1):
        filename = f"manrope-{index}.woff2"
        data = _fetch(url)
        if len(data) < 1000:
            raise RuntimeError(f"Downloaded font asset is unexpectedly small: {url}")
        (FONT_DIR / filename).write_bytes(data)
        replacements[url] = f"../fonts/manrope/{filename}"

    for remote, local in replacements.items():
        css = css.replace(remote, local)

    banner = (
        "/* AUTO-GENERATED by scripts/fetch_manrope.py. "
        "Do not edit manually. */\n"
    )
    CSS_PATH.write_text(banner + css.strip() + "\n", encoding="utf-8")
    print(f"Installed Manrope locally: {len(urls)} WOFF2 asset(s).")
    print(f"Generated: {CSS_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as exc:
        print(f"Manrope font installation failed: {exc}", file=sys.stderr)
        print(
            "An internet connection is required once during install/build so the "
            "application can cache Manrope locally.",
            file=sys.stderr,
        )
        raise SystemExit(1)
